language: python

matrix:
  include:
    - python: 2.7
      env: NUMPY=1.8 SCIPY=0.13 CASADIVERSION=2.4.0-rc2 DISPLAY=:99.0

notifications:
  email: false

before_install:
 - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH=/home/travis/miniconda/bin:$PATH
 - conda update --yes conda

 # - pip install --upgrade pip
 # - pip install setuptools --no-use-wheel --upgrade

install:
 - conda install --yes numpy=$NUMPY scipy=$SCIPY matplotlib nose mock
 - pip install coverage==3.7.1 coveralls python-coveralls nose-cov

 - wget http://sourceforge.net/projects/casadi/files/CasADi/$CASADIVERSION/linux/casadi-py27-np1.9.1-v$CASADIVERSION.tar.gz/download -O casadi-py27-np1.9.1-v$CASADIVERSION.tar.gz
 - mkdir $HOME/casadi-py27-np1.9.1-v$CASADIVERSION
 - tar -zxvf casadi-py27-np1.9.1-v$CASADIVERSION.tar.gz -C $HOME/casadi-py27-np1.9.1-v$CASADIVERSION

 - python setup.py install

before_script:
 - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/pymodules/python2.7
 - export PYTHONPATH=$PYTHONPATH:$HOME/casadi-py27-np1.9.1-v$CASADIVERSION

script:
 - nosetests --exe -v --with-cov

after_success:
 - coveralls --config_file .coveragerc
