language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# command to install dependencies
install:
 - travis_retry sudo apt-get install -qq libatlas3-base libgfortran3 liblapack3 libslicot0 python-numpy python-scipy python-matplotlib #coinor-libipopt-dev libmumps-seq-dev
 - travis_retry wget https://github.com/casadi/casadi/releases/download/2.2.0/python-casadi_2.2.0-2_amd64.deb
 - dpkg -i python-casadi_2.2.0-2_amd64.deb
 - rm python-casadi_2.2.0-2_amd64.deb
 - python setup.py install
# - "pip install ."
#  - "pip install -r requirements.txt"

# command to run tests
script:
  - python examples/ex1.py
  - nosetests pecas
