language: python

matrix:
  include:
    - python: 2.7
      env: NUMPY=1.8 SCIPY=0.13

notifications:
  email: false

before_install:
 - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH=/home/travis/miniconda/bin:$PATH
 - conda update --yes conda

install:
 - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
 - source activate test
 - conda install --yes numpy=$NUMPY scipy=$SCIPY matplotlib pip
 - pip install setuptools

 - wget http://sourceforge.net/projects/casadi/files/CasADi/2.4.0-rc1/linux/casadi-py27-np1.9.1-v2.4.0-rc1.tar.gz/download -O casadi-py27-np1.9.1-v2.4.0-rc1.tar.gz
 - mkdir casadi-py27-np1.9.1-v2.4.0-rc1
 - tar -zxvf casadi-py27-np1.9.1-v2.4.0-rc1-py.tar.gz -C casadi-py27-np1.9.1-v2.4.0-rc1

# - travis_retry wget http://sourceforge.net/projects/casadi/files/CasADi/2.3.0-rc2/Ubuntu-12.04/python-casadi_2.3.0rc2-2_amd64.deb/download -O python-casadi_2.3.0rc2-2_amd64.deb
# - sudo dpkg -i python-casadi_2.3.0rc2-2_amd64.deb
# - rm python-casadi_2.3.0rc2-2_amd64.deb

 - python setup.py install

before_script:
 - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/pymodules/python2.7
  -export PYTHONPATH=$PYTHONPATH:$HOME/casadi-py27-np1.9.1-v2.4.0-rc1

script:
 - python -c 'import numpy; print numpy.version.version'
 - nosetests -v --exe
