language: python
python:
  - "2.7"

before_install:
 # - travis_retry sudo apt-get install -y -qq python-numpy python-scipy python-matplotlib #liblapack3gf liblapack-dev libblas-dev libblas3gf #coinor-libipopt-dev libmumps-seq-dev
 - sudo apt-get autoremove -y libblas3gf liblapack3gf 
 - sudo apt-get install -y libgfortran3
 - travis_retry wget http://cz.archive.ubuntu.com/ubuntu/pool/main/b/blas/libblas3_1.2.20110419-7_amd64.deb
 - sudo dpkg -i libblas3_1.2.20110419-7_amd64.deb
 - rm libblas3_1.2.20110419-7_amd64.deb
 - travis_retry wget http://cz.archive.ubuntu.com/ubuntu/pool/main/l/lapack/liblapack3_3.5.0-2ubuntu1_amd64.deb
 - sudo dpkg -i liblapack3_3.5.0-2ubuntu1_amd64.deb
 - rm liblapack3_3.5.0-2ubuntu1_amd64.deb
 - travis_retry wget http://cz.archive.ubuntu.com/ubuntu/pool/main/p/python-numpy/python-numpy_1.8.1-1ubuntu1_amd64.deb
 - sudo dpkg -i python-numpy_1.8.1-1ubuntu1_amd64.deb
 - rm python-numpy_1.8.1-1ubuntu1_amd64.deb
 - travis_retry sudo apt-get install -y -qq python-scipy python-matplotlib #liblapack3gf liblapack-dev libblas-dev libblas3gf #coinor-libipopt-dev libmumps-seq-dev
 - travis_retry wget https://github.com/casadi/casadi/releases/download/2.2.0/python-casadi_2.2.0-2_amd64.deb
 - sudo dpkg -i python-casadi_2.2.0-2_amd64.deb
 - sudo apt-get install -y -f
 - rm python-casadi_2.2.0-2_amd64.deb

install:
 - python setup.py install

before_script:
 - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/pymodules/python2.7

script:
  - nosetests -v --exe
