language: python
python:
  - "2.7"

before_install:
 # - travis_retry sudo apt-get install -y -qq python-numpy python-scipy python-matplotlib #liblapack3gf liblapack-dev libblas-dev libblas3gf #coinor-libipopt-dev libmumps-seq-dev
 - travis_retry sudo apt-get install -y -qq python-scipy python-matplotlib #liblapack3gf liblapack-dev libblas-dev libblas3gf #coinor-libipopt-dev libmumps-seq-dev
 - travis_retry wget http://cz.archive.ubuntu.com/ubuntu/pool/main/p/python-numpy/python-numpy_1.8.1-1ubuntu1_amd64.deb
 - sudo dpkg -i python-numpy_1.8.1-1ubuntu1_amd64.deb
 - sudo apt-get install -y -f
 - rm python-numpy_1.8.1-1ubuntu1_amd64.deb
 # - pip install numpy --upgrade
 # - pip install scipy --upgrade
 - travis_retry wget https://github.com/casadi/casadi/releases/download/2.2.0/python-casadi_2.2.0-2_amd64.deb
 - sudo dpkg -i python-casadi_2.2.0-2_amd64.deb
 - sudo apt-get install -y -f
 - rm python-casadi_2.2.0-2_amd64.deb

install:
 - python setup.py install

before_script:
 - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/pymodules/python2.7

script:
  - nosetests -v --exe
