language: python
python:
  - "2.7"
# virtualenv:
#   system_site_packages: true
# command to install dependencies
before_install:
 - sudo apt-get update
 - travis_retry sudo apt-get install -y -qq python-numpy python-scipy python-matplotlib #liblapack3gf liblapack-dev libblas-dev libblas3gf #coinor-libipopt-dev libmumps-seq-dev
 - travis_retry wget https://github.com/casadi/casadi/releases/download/2.2.0/python-casadi_2.2.0-2_amd64.deb
 - sudo dpkg -i python-casadi_2.2.0-2_amd64.deb
 - sudo dpkg-query -c python-casadi
 - cat /var/lib/dpkg/info/python-casadi.md5sums
 - sudo apt-get install -y -f
 - rm python-casadi_2.2.0-2_amd64.deb
 # - sudo updatedb
 # - sudo locate casadi
install:
 - python setup.py install
# - "pip install ."
#  - "pip install -r requirements.txt"

# command to run tests
before_script:
 - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/dist-packages

script:
  # - python examples/ex1.py
  - nosetests --exe
