language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# command to install dependencies
install:
 - travis_retry sudo apt-get install -qq python-numpy python-scipy python-matplotlib liblapack3gf liblapack-dev libblas-dev libblas3gf #coinor-libipopt-dev libmumps-seq-dev
 - travis_retry wget https://github.com/casadi/casadi/releases/download/2.2.0/python-casadi_2.2.0-2_amd64.deb
 - sudo dpkg -i python-casadi_2.2.0-2_amd64.deb
 - sudo apt-get install -f
 - rm python-casadi_2.2.0-2_amd64.deb
 - python setup.py install
# - "pip install ."
#  - "pip install -r requirements.txt"

# command to run tests
script:
  # - python examples/ex1.py
  - nosetests pecas
